version: "1.0"
info:
  model: int-scaffold
packages:
- name: KusiTest2706Project
  gitServerName: Kusi_VCTest
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: JMS2waySSL
  gitServerName: SIQAPsurGit
  gitUrl: https://github.com/prabhakarsag
  gitUsername: prabhakarsag
  gitBranch: main
services:
- serviceName: project.kusitest2706.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: KusiTest2706Project
    version: "1.0"
- serviceName: project.kusitest2706.integrations:SIQAAdapterFlow
  packages:
  - name: KusiTest2706Project
    version: "1.0"
